MySchoolCollege/Controllers/AdministrationController.cs
using MySchoolCollege.Properties;
using MySchoolLibrary2018.Models.ModelViews;
using MySchoolLibrary2018.Models.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySchoolCollege.Controllers
{
    [Authorize(Roles = "Directeur,Surveillant")]
    public class AdministrationController : BaseController
    {
        private readonly ClasseRepository _classeRepository;
        private readonly EtablissementRepository _etablissementRepository;
        private readonly AnneeScolaireRepository _anneeScolaireRepository;
        private readonly ClasseDeBaseRepository _classeDeBaseRepository;

        private readonly int nLignesParPage = int.Parse(Resources.NombreLigneParPage);

        public AdministrationController()
        {
            _classeRepository = new ClasseRepository(Db);
            _etablissementRepository = new EtablissementRepository(Db);
            _anneeScolaireRepository = new AnneeScolaireRepository(Db);
            _classeDeBaseRepository = new ClasseDeBaseRepository(Db);
        }

        // GET: Administration
        public ActionResult Index()
        {
            return View();
        }

        //Gestion des classes
        public ActionResult Classes(int? page, int? annee)
        {
            var userOnLigne = Db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            int id = 0;
            if (userOnLigne.Etablissement != null)
            {

                id = userOnLigne.Etablissement.Id;
            }
            var etablissement = userOnLigne.Etablissement; //_etablissementRepository.Get(id);
            List<ClasseViewModel> model = new List<ClasseViewModel>();
            if (etablissement == null)
            {
                if (annee != 0)
                {
                    model = _classeRepository.GetList().Select(c => c.ToViewModel()).Where(c => c.AnneeScolaireId == annee).ToList();
                }
                else
                {
                    model = _classeRepository.GetList().Select(c => c.ToViewModel()).ToList();
                }

            }
            else
            {
                model = _classeRepository.GetList(etablissement.Id).Select(c => c.ToViewModel()).ToList();
            }

            var pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, nLignesParPage));
        }

        public ActionResult AjouterClasse()
        {
            var userOnLigne = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
            var etablissement = userOnLigne.Etablissement;
            var model = new ClasseViewModel();

            model.Professeurs = Db.Users.Where(u1 => u1.Etablissement.Id == etablissement.Id).Where(u => u.Fonction.Id == "PROFESSEUR").Select(p => new SelectListItem { Text = p.Prenom + " " + p.Nom, Value = p.Id }).ToList();
            model.AnneeScolaires = _anneeScolaireRepository.GetList().Select(a => new SelectListItem { Text = a.AnneeAcademique, Value = a.Id.ToString() }).ToList();
            model.Etablissements = _etablissementRepository.GetList().Where(et => et.Id == etablissement.Id).Select(e => new SelectListItem { Text = e.Nom, Value = e.Id.ToString() }).ToList();
            model.ClasseDeBases = _classeDeBaseRepository.GetList().Select(c => new SelectListItem { Text = c.Nom, Value = c.Id.ToString() }).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult AjouterClasse(ClasseViewModel model)
        {
            var userOnLigne = Db.Users.Where(u => u.UserName == User.Identity.Name).First();

            if (ModelState.IsValid)
            {
                model.CreerLe = DateTime.Now;
                model.CreerPar = userOnLigne;
                model.ModifierLe = DateTime.Now;
                model.Modifierpar = userOnLigne;

                model.ProfesseurPrincipal = Db.Users.Where(u => u.Id == model.ProfesseurPrinciplaId).FirstOrDefault();
                model.AnneeScolaire = _anneeScolaireRepository.Get(model.AnneeScolaireId);
                model.Etablissement = _etablissementRepository.Get(model.EtablissementId);
                model.ClasseDeBase = _classeDeBaseRepository.Get(model.ClasseDeBaseId);


                //On vérifie si la classe n'est pas déjà créée
                var xclasse = Db.Classes.Where(c => (c.AnneeScolaire.Id == model.AnneeScolaireId) && (c.Etablissement.Id == model.EtablissementId) && (c.ClasseDeBase.Id == model.ClasseDeBaseId)).FirstOrDefault();
                if (xclasse != null)
                {
                    ModelState.AddModelError("", "La classe est déjà ajoutée");
                }
                else
                {
                    var classe = model.ToModel();
                    try
                    {
                        _classeRepository.Add(classe);
                        TempData["Message"] = "Classe [" + classe.ClasseDeBase.Nom + "] ajoutée avec succès!";
                    }
                    catch
                    {
                        TempData["MessageErreur"] = "Erreur inattendue!";
                    }

                    return RedirectToAction("Classes");
                }

            }

            //Si on arrive ici ça veut dire qu'il ya un probléme
            var etablissement = userOnLigne.Etablissement;
            model.Professeurs = Db.Users.Where(u1 => u1.Etablissement.Id == etablissement.Id).Where(u => u.Fonction.Id == "PROFESSEUR").Select(p => new SelectListItem { Text = p.Prenom + " " + p.Nom, Value = p.Id }).ToList();
            model.AnneeScolaires = _anneeScolaireRepository.GetList().Select(a => new SelectListItem { Text = a.AnneeAcademique, Value = a.Id.ToString() }).ToList();
            model.Etablissements = _etablissementRepository.GetList().Where(et => et.Id == etablissement.Id).Select(e => new SelectListItem { Text = e.Nom, Value = e.Id.ToString() }).ToList();
            model.ClasseDeBases = _classeDeBaseRepository.GetList().Select(c => new SelectListItem { Text = c.Nom, Value = c.Id.ToString() }).ToList();

            return View(model);
        }

        public ActionResult ModifierClasse(int id)
        {
            var classe = _classeRepository.Get(id);
            if (classe == null)
            {
                return HttpNotFound();
            }
            var model = classe.ToViewModel();
            var userOnLigne = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
            var etablissement = userOnLigne.Etablissement;
            if (etablissement != null)
            {
                model.Professeurs = Db.Users.Where(u1 => u1.Etablissement.Id == etablissement.Id).Where(u => u.Fonction.Id == "PROFESSEUR").Select(p => new SelectListItem { Text = p.Prenom + " " + p.Nom, Value = p.Id }).ToList();
                model.Etablissements = _etablissementRepository.GetList().Where(et => et.Id == etablissement.Id).Select(e => new SelectListItem { Text = e.Nom, Value = e.Id.ToString() }).ToList();
            }
            else
            {
                model.Professeurs = Db.Users.Where(u => u.Fonction.Id == "PROFESSEUR").Select(p => new SelectListItem { Text = p.Prenom + " " + p.Nom, Value = p.Id }).ToList();
                model.Etablissements = _etablissementRepository.GetList().Select(e => new SelectListItem { Text = e.Nom, Value = e.Id.ToString() }).ToList();
            }

            model.AnneeScolaires = _anneeScolaireRepository.GetList().Select(a => new SelectListItem { Text = a.AnneeAcademique, Value = a.Id.ToString() }).ToList();
            model.ClasseDeBases = _classeDeBaseRepository.GetList().Select(c => new SelectListItem { Text = c.Nom, Value = c.Id.ToString() }).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult ModifierClasse(ClasseViewModel model)
        {
            var userOnLigne = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
            if (ModelState.IsValid)
            {

                model.ModifierLe = DateTime.Now;
                model.Modifierpar = userOnLigne;
                model.ProfesseurPrincipal = Db.Users.Where(u => u.Id == model.ProfesseurPrinciplaId).FirstOrDefault();
                model.AnneeScolaire = _anneeScolaireRepository.Get(model.AnneeScolaireId);
                model.Etablissement = _etablissementRepository.Get(model.EtablissementId);
                model.ClasseDeBase = _classeDeBaseRepository.Get(model.ClasseDeBaseId);

                //On vérifie si la classe n'est pas déjà créée
                var xclasse = Db.Classes.Where(c => (c.AnneeScolaire.Id == model.AnneeScolaireId) && (c.Etablissement.Id == model.EtablissementId) && (c.ClasseDeBase.Id == model.ClasseDeBaseId)).FirstOrDefault();
                if (xclasse != null && xclasse.Id != model.Id)
                {
                    ModelState.AddModelError("", "La classe est déjà ajoutée");
                }
                else
                {
                    var classe = _classeRepository.Get(model.Id);
                    model.CreerPar = classe.CreerPar;
                    model.ToSaveModel(classe);
                    try
                    {
                        _classeRepository.Update(classe);
                        TempData["Message"] = "Classe [" + classe.ClasseDeBase.Nom + "] modifiée avec succès!";
                    }
                    catch
                    {
                        TempData["MessageErreur"] = "Erreur inattendue!";
                    }

                    return RedirectToAction("Classes");
                }
            }
            //si on arrive ici ça veux dire qu'il ya un probleme
            var etablissement = userOnLigne.Etablissement;
            if (etablissement != null)
            {

MySchoolCollege/Views/Administration/AjouterClasse.cshtml
@model MySchoolLibrary2018.Models.ModelViews.ClasseViewModel
@{
    ViewBag.Title = "Ajouter une Classe";
}
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa  fa-pencil"></i>
                Classes
            </h1>
        </div>
    </div>
    <!-- widget grid -->
    <section id="widget-grid" class="">
        <!-- row -->
        <div class="row">

            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <h2><strong>Ajouter une </strong> <i>Classe</i></h2>

                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                            <input class="form-control" type="text">
                            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            @using (Html.BeginForm("AjouterClasse", "Administration", FormMethod.Post, new { @class = "smart-form" }))
                            {
                                @Html.AntiForgeryToken()
                                <header>Ajouter une classe</header>


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">
                                            <label class="select">
                                                @Html.DropDownListFor(model => model.AnneeScolaireId, Model.AnneeScolaires, "Année académique")
                                                <i></i>
                                                @Html.ValidationMessageFor(model => model.AnneeScolaireId, "", new { @class = "text-danger" })
                                            </label>

                                        </section>
                                        <section class="col col-6">
                                            <label class="input">
                                                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { placeholder = "Nom de la classe" }  })
                                                <i></i>
                                                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                                            </label>

                                        </section>
                                    </div>
                                    <section>

                                        <label class="select">
                                            @Html.DropDownListFor(model => model.EtablissementId, Model.Etablissements)
                                            <i></i>
                                            @Html.ValidationMessageFor(model => model.EtablissementId, "", new { @class = "text-danger" })
                                        </label>
                                    </section>
                                    <section>

                                        <label class="select">
                                            @Html.DropDownListFor(model => model.ProfesseurPrinciplaId, Model.Professeurs, "Professeur principal")
                                            <i></i>
                                            @Html.ValidationMessageFor(model => model.ProfesseurPrinciplaId, "", new { @class = "text-danger" })
                                        </label>
                                    </section>
                                    <section>

                                        <label class="select">
                                            @Html.DropDownListFor(model => model.ClasseDeBaseId, Model.ClasseDeBases, "Sélectionner une classe")
                                            <i></i>
                                            @Html.ValidationMessageFor(model => model.ClasseDeBaseId, "", new { @class = "text-danger" })
                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button class="btn btn-default" onclick="windows.history.back();">
                                        Annuler
                                    </button>
                                    <button class="btn btn-primary" type="submit">
                                        Ajouter
                                    </button>
                                </footer>

                            }


                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>
            <!-- WIDGET END -->
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-2" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <span class="widget-icon"> <i class="fa fa-question"></i> </span>
                        <h2 class="font-md"><strong>Guide</strong> <i>d'utilisation</i></h2>

                    </header>

                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body smart-form no-padding">
                            <header>Cette formulaire vous permez d'ajouter une classe</header>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->



            </article>
            <!-- WIDGET END -->
        </div>
        <!--end row-->
    </section>
    <!--end widget grid-->
</div>

MySchoolCollege/Views/Administration/Classes.cshtml
@model PagedList<MySchoolLibrary2018.Models.ModelViews.ClasseViewModel>
@using PagedList
@using PagedList.Mvc

@{
    ViewBag.Title = "Classes";
}

<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa fa-list-alt fa-pencil-square"></i>
                Classes
            </h1>
        </div>
    </div>
    @Html.Partial("_Message")
    <!-- widget grid -->
    <section id="widget-grid" class="">
        <!-- row -->
        <div class="row">

            <!-- NEW WIDGET START -->
            <article class="col-sm-12 ">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header role="heading">
                        <span class="widget-icon"> <i class="fa fa-pencil-square"></i> </span>
                        <h2><strong>Liste des</strong> <i>Classes</i></h2>

                    </header>

                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                            <input class="form-control" type="text">
                            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            <div id="dt_basic_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                <div class="dt-toolbar">
                                    <div class="col-xs-12 col-sm-6 hidden-xs">
                                        <div id="dt_basic_filter" class="dataTables_filter">
                                            <label>
                                                <a href="@Url.Action("AjouterClasse", "Administration")" class="form-control btn-default b"> <i>Ajouter</i> </a>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <table id="dt_basic" class="table table-striped table-bordered table-hover dataTable no-footer" width="100%" role="grid" aria-describedby="dt_basic_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th>
                                                Classe
                                            </th>
                                            <th>
                                                Base
                                            </th>
                                            <th>
                                                Etablissement
                                            </th>
                                            <th>
                                                Année scolaire
                                            </th>
                                            <th>
                                                Professeur principal
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var item in Model)
                                        {
                                            <tr role="row">
                                                <td>
                                                   @Html.ActionLink(@Html.DisplayFor(modelItem => item.Nom).ToHtmlString(),"VueClasse", new { id = item.Id})
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ClasseDeBase.Nom)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Etablissement.Nom)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AnneeScolaire.AnneeAcademique)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ProfesseurPrincipal.Prenom) @Html.DisplayFor(modelItem => item.ProfesseurPrincipal.Nom)

                                                </td>
                                                <td>
                                                    @Html.ActionLink("Modifier", "ModifierClasse", new { id = item.Id }) 
                                                    @if (User.IsInRole("Administrateur"))
                                                    {
                                  
                                                     @Html.ActionLink("Supprimer", "SupprimerClasse", new { id = item.Id })
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>

                                </table>
                                <div class="dt-toolbar-footer">
                                    <div class="col-sm-6 col-xs-12 hidden-xs">
                                        <div class="dataTables_info" id="dt_basic_info" role="status" aria-live="polite">
                                            Total @Model.Count/@Model.TotalItemCount  items
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-6">
                                        <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
                                            <!-- output a paging control that lets the user navigation to the previous page, next page, etc -->
                                            @Html.PagedListPager(Model, page => Url.Action("Classes", new { page }))
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end widget content -->


                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->
            </article>
            <!-- WIDGET END -->
        </div>
        <!-- end row -->
    </section>
    <!-- end widget grid -->
</div>