MySchoolCollege/Controllers/ParametreController.cs
using MySchoolLibrary2018.Models.ModelViews;
using MySchoolLibrary2018.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;
using MySchoolCollege.Properties;
using MySchoolLibrary2018.Models;
using System.Diagnostics;

namespace MySchoolCollege.Controllers
{
    [Authorize(Roles ="Administrateur")]
    public class ParametreController : BaseController
    {
        private readonly EtablissementRepository _etablissementRepository;
        private readonly TypeEtablissementRepository _typeEtablissementRepository;
        private readonly AnneeScolaireRepository _anneeScolaireRepository;
        private readonly PeriodeRepository _periodeRepository;
        private readonly NiveauRepository _niveauRepository;
        private readonly CycleRepository _cycleRepository;
        private readonly AutorisationRepository _autorisationRepository;
        private readonly FiliereRepository _filiereRepository;
        private readonly MentionRepository _mentionRepository;
        private readonly AvisCERepository _avisCERepository;
        private readonly MotifAbsenceRepository _motifAbsenceRepository;
        private readonly MotifRetardRepository _motifRetardRepository;
        private readonly MinistereRepository _ministereRepository;
        private readonly InspectionRepository _inspectionRepository;
        private readonly TypeInspectionRepository _typeInspectionRepository;
        private readonly ClasseDeBaseRepository _classeDeBaseRepository;

        private readonly int nLignesParPage = int.Parse(Resources.NombreLigneParPage);

        public ParametreController()
        {
            _etablissementRepository = new EtablissementRepository(Db);
            _typeEtablissementRepository = new TypeEtablissementRepository(Db);
            _anneeScolaireRepository = new AnneeScolaireRepository(Db);
            _periodeRepository = new PeriodeRepository(Db);
            _niveauRepository = new NiveauRepository(Db);
            _cycleRepository = new CycleRepository(Db);
            _autorisationRepository = new AutorisationRepository(Db);
            _filiereRepository = new FiliereRepository(Db);
            _mentionRepository = new MentionRepository(Db);
            _avisCERepository = new AvisCERepository(Db);
            _motifAbsenceRepository = new MotifAbsenceRepository(Db);
            _motifRetardRepository = new MotifRetardRepository(Db);
            _ministereRepository = new MinistereRepository(Db);
            _inspectionRepository = new InspectionRepository(Db);
            _typeInspectionRepository = new TypeInspectionRepository(Db);
            _classeDeBaseRepository = new ClasseDeBaseRepository(Db);
        }
        // GET: Parametre
        public ActionResult Index()
        {
            return View();
        }

        //Début type établissement
        public ActionResult TypesEtablissement(int? page)
        {
            List<TypeEtablissementViewModel> model = _typeEtablissementRepository.GetList().Select(t => t.ToViewModel()).ToList();
            var pageNumber = page ?? 1;
            return View(model.ToPagedList(pageNumber, nLignesParPage));
        }
        public ActionResult AjouterTypeEtablissement()
        {
            TypeEtablissementViewModel model = new TypeEtablissementViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult AjouterTypeEtablissement(TypeEtablissementViewModel model)
        {
            if (ModelState.IsValid)
            {
                var type = model.ToModel();
                try
                {
                    _typeEtablissementRepository.Add(type);
                    TempData["Message"] = "Type ajouté avec succès.";
                }
                catch
                {
                    TempData["MessageErreur"] = "Erreur inattendue!";
                }

                return RedirectToAction("TypesEtablissement");
            }
            return View(model);
        }

        public ActionResult SupprimerTypeEtablissement(string id)
        {
            var type = _typeEtablissementRepository.Get(id);
            if(type == null)
            {
                return HttpNotFound();
            }
            return View(type.ToViewModel());
        }

        [HttpPost]
        public ActionResult SupprimerTypeEtablissementConfirmation(string id)
        {
            try
            {
                _typeEtablissementRepository.Delete(id);
                TempData["Message"] = "Type supprimé avec succès";
            }
            catch
            {
                TempData["MessageErreur"] = "Erreur inattendue!";
            }

            return RedirectToAction("TypesEtablissement");
        }
        //Fin type établissement

        //Début Etablissement
        /// <summary>
        /// Voir les détails d'un établissement
        /// </summary>
        /// <param name="id">identifiant unique de l'établissement</param>
        /// <returns></returns>
        public ActionResult DetailsEtablissement(int id)
        {
            var etablissement = _etablissementRepository.Get(id);
            if( etablissement == null)
            {
                return HttpNotFound();
            }

            var model = etablissement.ToViewModel();
            return View(model);
        }

        /// <summary>
        /// La liste des établissements
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Etablissements(int? page)
        {
            List<EtablissementViewModel> model = _etablissementRepository.GetList().Select(e => e.ToViewModel()).ToList();
            var pageNumber = page ?? 1;
            //  
            return View(model.ToPagedList(pageNumber, nLignesParPage));
        }

        //GET: 
        [HttpGet]
        public ActionResult AjouterEtablissement()
        {
            var model = new EtablissementViewModel();
            var types = _typeEtablissementRepository.GetList().Select(s => new SelectListItem { Text = s.Description, Value = s.Id }).ToList();
            var inspections = _inspectionRepository.GetList().Select(s => new SelectListItem { Text = s.Nom, Value = s.Id.ToString()}).ToList();
            model.Types = types;
            model.Inspections = inspections;
            return View(model);
        }

        /// <summary>
        /// Ajouter un nouveau établissement
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AjouterEtablissement( EtablissementViewModel model)
        {
            if (ModelState.IsValid)
            {
                Etablissement etablissement = model.ToModel();
                
                etablissement.CreerPar = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
                etablissement.Modifierpar = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
               
                etablissement.Type = _typeEtablissementRepository.Get(model.TypeEtablissementId);
                etablissement.Inspection = _inspectionRepository.Get(model.InspectionId);
                etablissement.DateCreation = DateTime.Now;
                etablissement.DateModification = DateTime.Now;

                try
                {
                    _etablissementRepository.Add(etablissement);
                    TempData["Message"] = "Etablissement ajouté avec succés";
                    
                }
                catch
                {
                    TempData["MessageErreur"] = "Erreur inattendue!";
                }

                return RedirectToAction("Etablissements");

            }
            //si on arrive ici c'est à dire quelque chose ne va pas.
            var types = _typeEtablissementRepository.GetList().Select(s => new SelectListItem { Text = s.Description, Value = s.Id }).ToList();
            var inspections = _inspectionRepository.GetList().Select(s => new SelectListItem { Text = s.Nom, Value = s.Id.ToString() }).ToList();
            model.Types = types;
            model.Inspections = inspections;
            return View(model);
        }

        [HttpGet]
        public ActionResult ModifierEtablissement(int id)
        {
            //var model = new EtablissementViewModel();
            var etablissement = _etablissementRepository.Get(id);
            if(etablissement == null)
            {
                return HttpNotFound();
            }
            var types = _typeEtablissementRepository.GetList().Select(s => new SelectListItem { Text = s.Description, Value = s.Id }).ToList();
            var inspections = _inspectionRepository.GetList().Select(i => new SelectListItem { Text = i.Nom, Value = i.Id.ToString()}).ToList();
            

            var model = etablissement.ToViewModel();
            model.Types = types;
            model.Inspections = inspections;
            try
            {
                model.TypeEtablissementId = etablissement.Type.Id;
                model.InspectionId = etablissement.Inspection.Id;
            }
            catch
            {

            }
            
            return View(model);
        }

        [HttpPost]
        public ActionResult ModifierEtablissement(EtablissementViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                Etablissement etablissement = _etablissementRepository.Get(model.Id);
                model.ToSaveModel(etablissement);
                etablissement.Modifierpar = Db.Users.Where(u => u.UserName == User.Identity.Name).First();
                etablissement.CreerPar = Db.Users.Where(u => u.Id == model.CreerParId).First();
                etablissement.Type = _typeEtablissementRepository.Get(model.TypeEtablissementId);

MySchoolCollege/Views/Parametre/AjouterCycle.cshtml
@model MySchoolLibrary2018.Models.ModelViews.CycleViewModel
@{
    ViewBag.Title = "AjouterCycle";
}
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa fa-list-alt fa-arrow-circle-up"></i>
                Cycles
            </h1>
        </div>
    </div>
    @Html.Partial("_Message")
    <!-- widget grid -->
    <section id="widget-grid" class="">
        <!-- row -->
        <div class="row">

            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <h2><strong>Ajouter un </strong> <i>Cycle</i></h2>

                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                            <input class="form-control" type="text">
                            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            @using (Html.BeginForm("AjouterCycle", "Parametre", FormMethod.Post, new { @class = "smart-form" }))
                            {
                                @Html.AntiForgeryToken()
                                <header>Ajouter un cycle</header>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { placeholder = "Code" } })
                                                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                            </label>
                                        </section>
                                    </div>
                                    <section>
                                        <label class="input">
                                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { placeholder = "Description" } })
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button class="btn btn-default" onclick="windows.history.back();">
                                        Annuler
                                    </button>
                                    <button class="btn btn-primary" type="submit">
                                        Ajouter
                                    </button>
                                </footer>

                            }


                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>
            <!-- WIDGET END -->
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-2" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <span class="widget-icon"> <i class="fa fa-question"></i> </span>
                        <h2 class="font-md"><strong>Guide</strong> <i>d'utilisation</i></h2>

                    </header>

                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body smart-form no-padding">
                            <header>Cette formulaire vous permez d'ajouter un cycle</header>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->



            </article>
            <!-- WIDGET END -->
        </div>
        <!--end row-->
    </section>
    <!--end widget grid-->
</div>

MySchoolCollege/Views/Parametre/AjouterMention.cshtml
@model MentionViewModel
@using MySchoolLibrary2018.Models.ModelViews
@{
    ViewBag.Title = "Ajouter une Mention";
}
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa  fa-users"></i>
                Mentions
            </h1>
        </div>
    </div>
    <!-- widget grid -->
    <section id="widget-grid" class="">
        <!-- row -->
        <div class="row">

            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <h2><strong>Ajouter une </strong> <i>Mention</i></h2>

                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                            <input class="form-control" type="text">
                            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            @using (Html.BeginForm("AjouterMention", "Parametre", FormMethod.Post, new { @class = "smart-form" }))
                            {
                                @Html.AntiForgeryToken()
                                <header>Ajouter une mention</header>


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <fieldset>
                                    <div class="row">
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new {placeholder = "Description"}})
                                                @Html.ValidationMessageFor(model => model.Description,"", new { @class = "text-danger"})
                                            </label>
                                        </section>
                                    </div>
                                    <section>                                        
                                        <label class="checkbox">
                                            @Html.CheckBoxFor(model => model.AImprimer)
                                            <i></i>
                                            A imprimer dans le bulletin?
                                        </label>
                                    </section>
                                    <section>

                                        <label class="input">

                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button class="btn btn-default" onclick="windows.history.back();">
                                        Annuler
                                    </button>
                                    <button class="btn btn-primary" type="submit">
                                        Ajouter
                                    </button>
                                </footer>

                            }


                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>
            <!-- WIDGET END -->
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-2" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <span class="widget-icon"> <i class="fa fa-question"></i> </span>
                        <h2 class="font-md"><strong>Guide</strong> <i>d'utilisation</i></h2>

                    </header>

                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body smart-form no-padding">
                            <header>Cette formulaire vous permez d'ajouter une Mention</header>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->



            </article>
            <!-- WIDGET END -->
        </div>
        <!--end row-->
    </section>
    <!--end widget grid-->
</div>

MySchoolCollege/Views/Parametre/AjouterMinistere.cshtml
@model MySchoolLibrary2018.Models.ModelViews.MinistereViewModel

@{
    ViewBag.Title = "Ajouter un Ministere";
}
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa  fa-users"></i>
                Ministères
            </h1>
        </div>
    </div>
    <!-- widget grid -->
    <section id="widget-grid" class="">
        <!-- row -->
        <div class="row">

            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <h2><strong>Ajouter un </strong> <i>Ministère</i></h2>

                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                            <input class="form-control" type="text">
                            <span class="note"><i class="fa fa-check text-success"></i> Change title to update and save instantly!</span>

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            @using (Html.BeginForm("AjouterMinistere", "Parametre", FormMethod.Post, new { @class = "smart-form" }))
                            {
                                @Html.AntiForgeryToken()
                                <header>Ajouter un Ministère</header>


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <fieldset>

                                    <section class="">

                                        <label class="input">
                                            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { placeholder = "Nom de l'Organisme" } })
                                            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                                        </label>
                                    </section>

                                    <div class="row">
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { placeholder = "Téléphone" } })
                                                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                                            </label>
                                        </section>
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { placeholder = "Adresse" } })
                                                @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
                                            </label>
                                        </section>
                                    </div>
                                    <div class="row">
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Ville, new { htmlAttributes = new { placeholder = "Ville" } })
                                                @Html.ValidationMessageFor(model => model.Ville, "", new { @class = "text-danger" })
                                            </label>
                                        </section>
                                        <section class="col col-6">

                                            <label class="input">
                                                @Html.EditorFor(model => model.Pays, new { htmlAttributes = new { placeholder = "Pays" } })
                                                @Html.ValidationMessageFor(model => model.Pays, "", new { @class = "text-danger" })
                                            </label>
                                        </section>
                                    </div>

                                </fieldset>
                                <footer>
                                    <button class="btn btn-default" onclick="windows.history.back();">
                                        Annuler
                                    </button>
                                    <button class="btn btn-primary" type="submit">
                                        Ajouter
                                    </button>
                                </footer>

                            }


                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>
            <!-- WIDGET END -->
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-2" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false">
                    <!-- widget options:
                        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                        data-widget-colorbutton="false"
                        data-widget-editbutton="false"
                        data-widget-togglebutton="false"
                        data-widget-deletebutton="false"
                        data-widget-fullscreenbutton="false"
                        data-widget-custombutton="false"
                        data-widget-collapsed="true"
                        data-widget-sortable="false"

                    -->
                    <header>
                        <span class="widget-icon"> <i class="fa fa-question"></i> </span>
                        <h2 class="font-md"><strong>Guide</strong> <i>d'utilisation</i></h2>

                    </header>

                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body smart-form no-padding">
                            <header>Cette formulaire vous permez d'ajouter un Ministère</header>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->



            </article>
            <!-- WIDGET END -->
        </div>
        <!--end row-->
    </section>
    <!--end widget grid-->
</div>